Merge pull request from kec/HLDN-198-swagger-ft to main
commit ae5333d4c507fa6e2261839a83225fd1c6be8aa7 
Author: Daniel Kec <daniel.kec@oracle.com> 
Date: Wed Jun 25 11:51:50 UTC 2025 
	 HLDN-198 [Identity] NoSuchMethodError - SwaggerClientUtil.getInstanceOfCircuitBreaker()